apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-cm
data:
  #ATTACKED_HOST: "http://spring-music-wise-lizard.apps.tt-stg02.cf.t-mobile.com"
  ATTACKED_HOST: http://service1.apps.tt-stg02.cf.t-mobile.com
