apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
 
   from locust import HttpLocust, TaskSet, task

   class UserBehavior(TaskSet):
     def on_start(self):
       pass
    
     def on_stop(self):
       pass

     @task(1)
     def index(self):
       self.client.get("/")

     @task(2)
     def albums(self):
       self.client.get("/helloService1")

   class WebsiteUser(HttpLocust):
      print('Inside WebsiteUser...')
      host = 'service1.apps.tt-stg02.cf.t-mobile.com'
      task_set = UserBehavior
      min_wait = 2000
      max_wait = 10000
